name: Template Tests
on:
  pull_request: {}
  push:
    branches: [main]
jobs:
  integration:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      matrix:
        db_config:
          - want: "n"
          - want: "y"
            provider: prisma
            db: sqlite
            migrate: "y"
          - want: "y"
            provider: prisma
            db: PostgreSQL
            migrate: "n"
            migrate_command: |
              npx prisma migrate dev --name init
    steps:
      - uses: actions/checkout@v3
        with:
          path: "repo"
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Remix Init
        env:
          WANT_DB: ${{ matrix.db_config.want }}
          DB_PROVIDER: ${{ matrix.db_config.provider }}
          DB: ${{ matrix.db_config.db }}
          RUN_MIGRATIONS: ${{ matrix.db_config.migrate }}
        run: |
          npx create-remix@latest --install --typescript --template ./repo ./template
      
      - name: List Files
        run: ls ./template

      - name: Setup docker compose
        if: ${{ matrix.db_config.migrate_command }}
        uses: isbang/compose-action@v1.4.0
        with:
          compose-file: "./template/docker-compose.yml"

      - name: Playwright Cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
      - name: Install Playwright Browsers
        working-directory: ./template
        run: npx playwright install --with-deps
      
      - name: Migrate DB
        if: ${{ matrix.db_config.migrate_command }}
        working-directory: ./template
        run: ${{ matrix.db_config.migrate_command }}

      - name: Run Playwright tests
        working-directory: ./template
        run: npx playwright test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
