name: Template Tests
on:
  pull_request: {}
  push:
    branches: [main]
jobs:
  integration:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      matrix:
        db_config:
          - provider: false
          - provider: prisma
            db: sqlite
            migrate: true
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Remix Init
        env:
          DB_PROVIDER: ${{ MATRIX.db_config.provider }}
          DB: ${{ MATRIX.db_config.db }}
          RUN_MIGRATIONS: ${{ MATRIX.db_config.migrate }}
        run: |
          npx create-remix@latest --install --typescript --template jacob-ebey/remix-dashboard-template .
      
      - name: Playwright Cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
